name: sunny_dart
version: 0.11.1
homepage: https://github.com/SunnyApp/sunny_dart
description: Core utilities used by sunny packages
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: 2.10.0
  chunked_stream: 1.4.1
  collection: 1.17.0
  crypto: 3.0.2
  equatable: 2.0.5
  phone_numbers_parser: 7.0.0
  intl: 0.17.0
  logging: 1.1.1
  meta: 1.8.0
  pedantic: 1.11.1
  recase: 4.0.0
  stream_transform: 2.0.0
  timezone: 0.9.0
  uuid: 3.0.7
  inflection3: 0.5.3+2
  uri: 1.0.0
  platform_detect2: 1.5.0+2
  info_x:
    git:
      url: https://github.com/ginger-io/flutter-plugins.git
      ref: master
      path: packages/info_x
  dartxx:
    git:
      url: https://github.com/ginger-io/flutter-plugins.git
      ref: master
      path: packages/dartxx

dev_dependencies: 
  flutter_test: 
    sdk: flutter
