include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_void_async: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    literal_only_boolean_expressions: false
    no_adjacent_strings_in_list: false
    non_constant_identifier_names: false
    omit_local_variable_types: false
    prefer_const_constructors: false
    require_trailing_commas: true
    slash_for_doc_comments: false
    unawaited_futures: true
    use_function_type_syntax_for_parameters: false
    use_key_in_widget_constructors: false


analyzer:
  exclude:
    - 'lib/generated/**'
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    todo: ignore
    unused_catch_clause: ignore
